a.out: main.o wypiszSkorowidz.o inicjujSkorowidz.o szukajSlow.o
	$(CC) $(-Wall) -o wyszukaj $(^)

main.o: skorowidz.h
wypiszSkorowidz.o: skorowidz.h
inicjujSkorowidz.o: skorowidz.h
szukajSlow.o: skorowidz.h
